# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Register_Form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Register_Form(object):
    def setupUi(self, Register_Form):
        Register_Form.setObjectName("Register_Form")
        Register_Form.resize(291, 281)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icon/APP_icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Register_Form.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Register_Form)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.user = QtWidgets.QLabel(self.centralwidget)
        self.user.setObjectName("user")
        self.gridLayout.addWidget(self.user, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.pass1 = QtWidgets.QLabel(self.centralwidget)
        self.pass1.setObjectName("pass1")
        self.gridLayout.addWidget(self.pass1, 2, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.pass2 = QtWidgets.QLabel(self.centralwidget)
        self.pass2.setObjectName("pass2")
        self.gridLayout.addWidget(self.pass2, 3, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 3, 1, 1, 1)
        self.idcard = QtWidgets.QLabel(self.centralwidget)
        self.idcard.setObjectName("idcard")
        self.gridLayout.addWidget(self.idcard, 4, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 4, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        Register_Form.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Register_Form)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 291, 22))
        self.menubar.setObjectName("menubar")
        Register_Form.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Register_Form)
        self.statusbar.setObjectName("statusbar")
        Register_Form.setStatusBar(self.statusbar)

        self.retranslateUi(Register_Form)
        self.pushButton.clicked.connect(Register_Form.register) # type: ignore
        self.pushButton_2.clicked.connect(Register_Form.back) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Register_Form)

    def retranslateUi(self, Register_Form):
        _translate = QtCore.QCoreApplication.translate
        Register_Form.setWindowTitle(_translate("Register_Form", "人脸签到系统-注册"))
        self.label.setText(_translate("Register_Form", "注册"))
        self.user.setText(_translate("Register_Form", "用户名"))
        self.name.setText(_translate("Register_Form", "姓名"))
        self.pass1.setText(_translate("Register_Form", "密码"))
        self.pass2.setText(_translate("Register_Form", "重复密码"))
        self.idcard.setText(_translate("Register_Form", "身份证号"))
        self.pushButton.setText(_translate("Register_Form", "注册"))
        self.pushButton_2.setText(_translate("Register_Form", "返回"))
