# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Stu_Inquiry_Form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Stu_Inquiry_Form(object):
    def setupUi(self, Stu_Inquiry_Form):
        Stu_Inquiry_Form.setObjectName("Stu_Inquiry_Form")
        Stu_Inquiry_Form.resize(715, 496)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icon/APP_icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Stu_Inquiry_Form.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Stu_Inquiry_Form)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)
        Stu_Inquiry_Form.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Stu_Inquiry_Form)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 715, 22))
        self.menubar.setObjectName("menubar")
        Stu_Inquiry_Form.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Stu_Inquiry_Form)
        self.statusbar.setObjectName("statusbar")
        Stu_Inquiry_Form.setStatusBar(self.statusbar)

        self.retranslateUi(Stu_Inquiry_Form)
        self.pushButton.clicked.connect(Stu_Inquiry_Form.back) # type: ignore
        self.tableWidget.cellDoubleClicked['int','int'].connect(Stu_Inquiry_Form.select) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Stu_Inquiry_Form)

    def retranslateUi(self, Stu_Inquiry_Form):
        _translate = QtCore.QCoreApplication.translate
        Stu_Inquiry_Form.setWindowTitle(_translate("Stu_Inquiry_Form", "学生签到查询"))
        self.pushButton.setText(_translate("Stu_Inquiry_Form", "返回"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Stu_Inquiry_Form", "课程名称"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Stu_Inquiry_Form", "签到情况"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Stu_Inquiry_Form", "学号"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Stu_Inquiry_Form", "姓名"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Stu_Inquiry_Form", "签到时间"))
