# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Stu_Inquiry_Form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Stu_Inquiry_Form(object):
    def setupUi(self, Stu_Inquiry_Form):
        Stu_Inquiry_Form.setObjectName("Stu_Inquiry_Form")
        Stu_Inquiry_Form.resize(791, 595)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icon/APP_icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Stu_Inquiry_Form.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Stu_Inquiry_Form)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.columnView = QtWidgets.QColumnView(self.centralwidget)
        self.columnView.setObjectName("columnView")
        self.gridLayout.addWidget(self.columnView, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)
        Stu_Inquiry_Form.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Stu_Inquiry_Form)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 791, 22))
        self.menubar.setObjectName("menubar")
        Stu_Inquiry_Form.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Stu_Inquiry_Form)
        self.statusbar.setObjectName("statusbar")
        Stu_Inquiry_Form.setStatusBar(self.statusbar)

        self.retranslateUi(Stu_Inquiry_Form)
        self.pushButton.clicked.connect(Stu_Inquiry_Form.back) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Stu_Inquiry_Form)

    def retranslateUi(self, Stu_Inquiry_Form):
        _translate = QtCore.QCoreApplication.translate
        Stu_Inquiry_Form.setWindowTitle(_translate("Stu_Inquiry_Form", "学生签到查询"))
        self.pushButton.setText(_translate("Stu_Inquiry_Form", "返回"))
